networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - '3001:3001'
    depends_on:
      - redis
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
        POSTGRES_USER: pikachu
        POSTGRES_PASSWORD: pikachu
        POSTGRES_DB: pokemon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
